comm

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -14,6 +14,6 @@ jobs:
       - name: "Failed step"
         run: |
           echo "I will fail"
-          set +e
+          set +e            #prevent step failure when cmd fails (set -e by def)
           ls sdfsdfs
-          echo "Goodby"
+          echo "Goodbye"
